#Thread Instance Attribiuts
from threading import Thread

thread = Thread()
print("After create instance from threading.Thread")
print(f"thread.name : {thread.name}")
print(f"thread.deamon : {thread.daemon}")
print(f"thread.ident : {thread.ident}")
print(f"thread.native_id : {thread.native_id}")
print(f"thread.is_alive : {thread.is_alive()}")
thread.start()
print("\nAfter start()")
print(f"thread.name : {thread.name}")
print(f"thread.deamon : {thread.daemon}")
print(f"thread.ident : {thread.ident}")
print(f"thread.native_id : {thread.native_id}")
print(f"thread.is_alive : {thread.is_alive()}")
thread.join()
print("\nAfter join()")
print(f"thread.name : {thread.name}")
print(f"thread.deamon : {thread.daemon}")
print(f"thread.ident : {thread.ident}")
print(f"thread.native_id : {thread.native_id}")
print(f"thread.is_alive : {thread.is_alive()}")